Point72/csp

csp/__init__.py
dev-environment.yml
pyproject.toml

This adds and fixes names for dependencies needed by the examples.
It also imports the `stats` module into `csp` since one of the examples used `csp.stats` without explicitly importing it.

Fixes for examples

---

.github/CODE_OF_CONDUCT.md
csp/examples/e_23_cpp_example/pyproject.toml
csp/examples/e_24_cpp_struct_example/pyproject.toml
pyproject.toml

Fix up metadata in `pyproject.toml` and update email addresses across the codebase to use the central one instead of personal ones.
fixes #16

Clean up metadata and email references

---

.github/workflows/build.yml
Makefile
csp/adapters/db.py
csp/adapters/output_adapters/parquet.py
csp/adapters/parquet.py
csp/tests/adapters/test_db.py
dev-environment.yml
pyproject.toml

This PR adds support for `sqlalchemy>=2` for the `DBReader` adapter.

Support sqlalchemy>=2

---

csp/tests/test_showgraph.py

Graphviz is not a required dependency, and we plan on enabling interactive graph viewing with something like [ipydagred3](https://github.com/timkpaine/ipydagred3) as an alternative shortly anyway

Skip graphviz tests if not installed locally

---

README.md

Tiny change, I think it makes sense to show the output in the first example you see when you visit the site 😅. Also removed the `csp.multiply` to keep it as simple as possible.

Show result of first example in readme

---

.github/workflows/build.yml

As per title, it seems like the `macos-12` build is intermittently refusing to detect our various caches, and I've observed it failing to acquire a GitHub runner at least once. Since these are the steps we run on every PR, we want them to be as fast as possible. Furthermore, since our maintainers are using M1-based Macs exclusively (at this time), it's not strictly necessary for us to produce x86 wheels to test on each PR.

Drop macos-12 (x86) build in frequent CI

---

csp/impl/types/instantiation_type_resolver.py
csp/tests/test_caching.py
csp/tests/test_engine.py
csp/tests/test_type_checking.py

Add function names to type resolver errors and properly report when the return value is the conflicting type

---

.github/workflows/build.yml

Really minor copy-paste error, i dropped a keyword to allow for manual runs to do a full build.

Fix copy-paste error with missing inputs block

---

.github/workflows/build.yml

These are not available according to:
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
So we will skip building wheels on these for now. `cibuildwheel` might still work, we can reenable support later if necessary.

Drop py3.8 and py3.9 from macos-14

---

dev-environment.yml

Using micromamba, the commands to use conda-forge are slightly different than https://github.com/Point72/csp/wiki/99.-Developer#conda
To make the workflow more robust, we can include the channel selection (and optionally, the dev environment name) in the environment.yml file itself.

Add channel selection to dev-environment.yml file

---

dev-environment.yml

@robambalu hit issues with the self-signed SSL certificates on internal dev machines and conda's git, so let's remove it and just document that people need git installed.
Also adding `cyrus-sasl`, which it turns out is necessary if librdkafka is getting built on a machine with kerberos set up.

Remove git and ass cyrus-sasl to dev environment

---

.github/workflows/build.yml
CMakeLists.txt
csp/tests/test_profiler.py
pyproject.toml
setup.py

This PR does three things:
- fix missing runtime dependency for python 3.8
- skip profiling test code if graphviz package missing (xref https://github.com/Point72/csp/pull/30)
- reenable sdist tests on full builds
"Full" build: https://github.com/Point72/csp/actions/runs/7855760939

Add dependency for python 3.8, reenable sdist

---

.github/workflows/build.yml

Doing this on top of #53 because of a fix in that PR. That should be merged first.
I got a request from @robambalu to add python3.8 linux wheels since there are some users who need that. There's a comment that we're not running these builds except on full runs to reduce CI usage. Opening this PR to see what the additional impact of these builds are now that we have caching fully working.

Add python3.8 linux wheel builds

---

csp/random.py
csp/tests/test_random.py
pyproject.toml

In order to write more convincing examples for more complex cases, we need a timer that ticks at irregular (pseudo-random) intervals. Furthermore, we also need something that ticks random floats and numpy arrays to simulate live data streams. 
Rather than keep this code in the examples folder, I chose to put it in csp.random so that it could be more widely used by others for examples, testing or as a building block in csp applications. To illustrate real "Monte Carlo" simulation use cases of csp, I implemented the random timer as a proper Poisson process and the random array generator as a proper multi-dimensional Brownian Motion, each with time-varying input parameters (which is relatively easy in csp). These are the two most common building blocks for stochastic processes.

Adding poisson_timer and brownian_motion to new csp.random module

---

csp/stats.py
csp/tests/test_stats.py

The csp.stats function list_to_numpy should return a 1DArray type since it only produces 1-dimensional array outputs. This can lead to downstream issues when users explicitly type their nodes to accept Numpy1DArray time-series inputs.

csp.stats.list_to_numpy should return a 1DArray, not an NDArray

---

cpp/csp/cppnodes/statsimpl.h

Summary of changes
1) Removed PBDS dependence in order statistics. If gcc is being used we used the PBDS tree, if not we use a std::multiset. The downside of this is that for Quantile/Rank, we need to iterate on the set to find the desired value which is O(n). Before, in the PBDS order statistics tree, the complexity of find is O(log n). I did research on replacing the pbds tree and there is no readily available equivalent data structure. I will open an issue as a good starter task for someone to implement a data structure for this use.
2) Realized I could do ArgMinMax more efficiently. With the pbds tree it was O(log n) insert/delete and find. Using the AscendingMinima monotonic queue, it's O(1) amortized for all those operations.

Remove GNU PBDS dependence in stats classes and improve ArgMinMax implementation

---

.github/workflows/build.yml

Not sure how to make ASCII art matching the other jobs

Add a workflow job to automate uploading to testpypi

---

.github/workflows/build.yml

I temporarily added this PR branch to the allowed branches for actions runs and ran this on my fork: https://github.com/ngoldbaum/csp/actions/runs/7908948300
The github release workflow failed, but it should work on the main repo because [forks can't grant write permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#changing-the-permissions-in-a-forked-repository).
Once this is merged I think we're ready to test the full release process by pushing a tag to the main repo.

Upload release artifacts to github releases

---

.github/workflows/build.yml

but at job level so as to not interfere with other permissions

Readd id-token permission for pypi

---

Makefile

Now that we have no warnings from this we can use `--strict` to keep them from reappearing.

use `twine check --strict` in dist-check

---

csp/adapters/slack.py
csp/tests/adapters/test_slack.py
pyproject.toml

Still needs a lot of work, just putting this draft PR up so its out there
fixes: https://github.com/Point72/csp/issues/17
ref: https://github.com/Point72/csp/issues/35
MVP:
```python
import csp
from csp import ts
from csp.adapters.slack import SlackAdapterManager, SlackMessage
SLACK_APP_TOKEN = "xapp-..."
SLACK_BOT_TOKEN = "xoxb-..."
@csp.node
def node(msg: ts[SlackMessage]) -> ts[SlackMessage]:
if csp.ticked(msg):
text = f"Hello <@{msg.user_id}>!"
return SlackMessage(
channel=msg.channel,
channel_id=msg.channel_id,
msg=text,
)
def graph():
am = SlackAdapterManager(SLACK_APP_TOKEN, SLACK_BOT_TOKEN)
am.publish(node(am.subscribe()))
csp.run(graph, realtime=True)
```

Add slack message adapter

---

cpp/csp/python/Conversions.h
csp/tests/impl/test_struct.py

Previously, the following code would result in a seg fault:
```
import csp
class StructOfGenericStruct(csp.Struct):
a: csp.Struct
if _name_ == "_main_":
ms = StructOfGenericStruct()
ms.a = None
```
This change fixes that issue so that we gracefully throw an error with a useful message. 
```
TypeError: PyStruct.cpp:setattr:449:TypeError: on field 'a' : Invalid struct type, expected struct got NoneType
```

Fix invalid access to a struct meta name when the struct is a base struct

---

README.md

https://github.com/Point72/csp/pull/120#discussion_r1504949399 did not mention that the link is BROKEN 😆 
Fixes that.

Fix second typo in pyproject.toml for python versions link

---

.github/workflows/build.yml
pyproject.toml

This fixes an error reported by @AdamGlustein:
<details>
```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/data01/home/user/hfalgo_ext/python/Python-3.8.12/lib/python3.8/site-packages/csp/__init__.py", line 3, in <module>
from csp.baselib import *
File "/data01/home/user/hfalgo_ext/python/Python-3.8.12/lib/python3.8/site-packages/csp/baselib.py", line 18, in <module>
from csp.impl.wiring import DelayedEdge, Edge, OutputsContainer, graph, …
```

Set minimum numpy version to avoid ABI mismatch error

---

.github/workflows/build.yml
.github/workflows/publish_wiki.yml
docs/wiki/0.-Introduction.md
docs/wiki/1.-Generic-Nodes-(csp.baselib).md
docs/wiki/2.-Math-Nodes-(csp.math).md
docs/wiki/3.-Statistics-Nodes-(csp.stats).md
docs/wiki/4.-Random-Time-Series-Generation-(csp.random).md
docs/wiki/5.-Adapters.md
docs/wiki/6.-Dynamic-Graphs.md
docs/wiki/7.-csp.Struct.md
docs/wiki/8.-Profiler.md
docs/wiki/9.-Caching.md
docs/wiki/99.-Developer.md
docs/wiki/Home.md

Closes #112 
~~Currently, we can't test the workflow until the PR is merged. However, I think we can temporarily enable runs on PRs to test it.~~
Additional notes added inline.

Move wiki docs into repo

---

docs/wiki/98.-Building-From-Source.md
docs/wiki/99.-Developer.md
docs/wiki/Home.md

* Moves the instructions that are currently in the "Developer" page into a new "Building from Source" page. 
* Adds the developer guide content from #117 to the "Developer" page.
* Link to both pages from the docs homepage.
Here's how it looks on my fork:
[homepage](https://github.com/ngoldbaum/csp/wiki)
[build instructions](https://github.com/ngoldbaum/csp/wiki/98.-Building-From-Source)
[developer guide](https://github.com/ngoldbaum/csp/wiki/99.-Developer)

Add developer guide and move build instructions to their own page

---

vcpkg.json

cc @robambalu, he says this solves the error he was running into.
I have a test script for this but it look like it will be a pain to get kerberos and `cyrus-sasl` installed on the github actions runners, so punting on that for now.

Build librdkafka with ssl support

---

csp/math.py
csp/tests/test_math.py

This makes `test_sdist` fail on a "full" test run: https://github.com/ngoldbaum/csp/actions/runs/8269123488/job/22623671505
I'm not sure offhand why `test_math_unary_ops` doesn't run in the regular tests.

Replace usages of math.exp2 on python older than 3.11

---

.bumpversion.cfg
CMakeLists.txt
csp/__init__.py
pyproject.toml
setup.py

The full tests passed on my fork: https://github.com/ngoldbaum/csp/actions/runs/8273957567
Once this is merged someone with access will need to tag `v0.0.2` for 781bf7e and manually push the tag to the repo. I should have access so I'll do it if I end up self-merging.

Bump version: 0.0.1 → 0.0.2

---

.github/workflows/build.yml

There's not much point in setting up python and then not running the tests, so let's skip the whole workflow except on full runs.

skip sdist tests except on full runs

---

csp/tests/impl/test_struct.py

Small PR to run autofixer. Unlike `black`, `ruff` does not fail if it would make non-linter-error format-only changes.

Run autofixer

---

csp/adapters/slack.py
csp/tests/adapters/test_slack.py

This PR addes SSL passthrough to the [Slack SDK's WebClient](https://slack.dev/python-slack-sdk/web/index.html). This is necessary in certain enterprise contexts.

Add ssl passthrough for slack adapter

---

Makefile
conda/dev-environment-linux.yml
cpp/tests/core/CMakeLists.txt
cpp/tests/engine/CMakeLists.txt
setup.py

Depends on https://github.com/Point72/csp/pull/162 to avoid conflicts
- Re-enable C++ tests
- Build C++ tests by default
- Run C++ tests by default via `make build` command
Note: I was lazy and used a bash for loop. Windows will probably be unhappy.

Re-enable C++ testing

---

.github/workflows/build.yml

~~full build: https://github.com/Point72/csp/actions/runs/8453489172~~
full build: https://github.com/Point72/csp/actions/runs/8454482996

clean up ci/cd code and ensure mac tests run

---

docs/wiki/3.-Statistics-Nodes-(csp.stats).md

The link to the quantile documentation was broken (and the formatting was wrong for median and quantile).

Fix documentation for median and quantile functions

---

cpp/csp/python/CMakeLists.txt
cpp/csp/python/PyStruct.cpp
cpp/csp/python/PyStructToJson.cpp
cpp/csp/python/PyStructToJson.h
csp/impl/struct.py
csp/tests/impl/test_struct.py

This PR adds the `to_json` method for structs.
With this, we can efficiently convert struct objects into json strings and communicate with other third-party endpoints using the JSON protocol.
For example,
```
class EmptyCspStruct(csp.Struct):
class CspStruct(csp.Struct):
a: int = 0
b: str = "str"
c: list = 3.14
d: EmptyCspStruct = EmptyCspStruct()
obj = CspStruct()
obj.to_json() # "{'a': 0, 'b': 'str', 'c': 3.14, 'd': {}}"
```
This change also supports parsing some Python specific `DialectGenericType` objects when converting structs into json strings. The list of Python specific types supported is `list, dict, and tuple`. In addition, Python's datetime types (`datetime, date, time, timedelta`) are also supported as they are natively supported by csp. 
```
class CspStruct(csp.Struct):
a: …
```

Add to_json method for structs

---

cpp/csp/adapters/websocket/ClientAdapterManager.cpp

I forgot, the reason I check the input adapter in the callback is because the input adapter is initialized after the adapter manager is created meaning that the on message callback would never get set.

websockets-adapter revert check for input adapter

---

.github/CODEOWNERS

This just makes 2 changes.
1. Alphabetize the packaging block, add `vcpkg.json`
2. I almost missed in https://github.com/Point72/csp/pull/152 so adding @ptomecek so there's another set of eyes/notifications, changes to `vcpkg.json` need to yield changes in `NOTICE` (via [`make notice`](https://github.com/Point72/csp/blob/47ec0dc4ae842d245910ac929b014018397815bb/Makefile#L163)) due to our use of statically linked packages, and nothing should modify `LICENSE`

Update codeowners for license check

---

cpp/csp/python/CMakeLists.txt
cpp/csp/python/Conversions.h
cpp/csp/python/InitHelper.h
cpp/csp/python/PyStruct.cpp
cpp/csp/python/PyStructList.h
cpp/csp/python/PyStructList.hi
csp/impl/struct.py
csp/tests/impl/test_struct.py

This change fixes the issue when users create a csp.Struct with a typed list field (`[int]`) and try to modify this list field in Python, only to find that their changes are lost. The issue occurred because the typed list fields are stored as C++ vectors, and Python changes to those fields are not mirrored on them by mutating operations. My change implements such mirroring by creating a wrapper type for typed list fields, PyStructList, and capturing all list-mutating Python operations via Python C API.

Override Python list modifying methods to capture and preserve changes to Struct list fields

---

cpp/csp/python/PyStructToJson.cpp
csp/tests/impl/test_struct.py

This PR fixes a bug in #182 where special float were not properly handled.
Special handling for `NaN`s and `+/-Inf`s has been added and these special float will now get converted to `null`s.
```
class A(csp.Struct):
fl_nan: float
fl_pinf: float
fl_ninf: float
a = A(fl_nan = float('nan'), fl_pinf = float('inf'), fl_ninf = float('-inf'))
a.to_json() == "{'fl_nan':null, 'fl_pinf':null, 'fl_ninf':null}"
```

Fix to_json serialization for floats

---

cpp/csp/python/PyStructToJson.cpp
csp/tests/impl/test_struct.py

This PR extends #182 by natively parsing None objects in csp.

Parse None natively in to_json method

---

cpp/csp/python/PyStructList.hi
csp/impl/struct.py
csp/tests/impl/test_struct.py

Also make the newly implemented `PyStructList` type constructible as a list.

Maintain the type of a list-derived object when converting a struct in to_dict

---

docs/wiki/dev-guides/Build-CSP-from-Source.md
docs/wiki/dev-guides/Contribute.md

- Revert changes made in https://github.com/Point72/csp/pull/142/commits/29e209b94574c16d22126b8a584fdeebb8876105
- Add back some changes lost/overridden in the docs-restructure
- Add back https://github.com/Point72/csp/commit/eed014cad87dfd2d15f728651617cd8962ba43eb#diff-601ce1bcfcbfabc32cec76f24a8581c736ee96543fc3242612be07a8e58000efL60-L71
- Add note about DCO in `Contribute.md`

Re-apply lost updates in dev guides

---

cpp/csp/engine/RootEngine.cpp
cpp/csp/engine/RootEngine.h
cpp/csp/python/PyNode.cpp
cpp/csp/python/csptestlibimpl.cpp
csp/tests/test_engine.py

Fix interrupt handling issues in csp: ensure first node is stopped and reset signaled flag across runs

---

cpp/csp/cppnodes/baselibimpl.cpp

Missing cast from vector value to `ElemT`, which for bool would be a vector value of unsigned char.  This was triggering a CSP_ASSERT in debug builds

minor bugfix to unroll cppimpl

---

docs/wiki/dev-guides/Local-Development-Setup.md
docs/wiki/dev-guides/Release-Process.md

This updates the release instructions in response to some feedback @robambalu shared after doing the 0.0.4 release and after #244.
It seems most of the maintainers at Point72 are directly pushing to the main repo, so I updated the instructions to match that common usage instead of the uncommon fork-based workflow that I originally assumed people would use. I've updated the note about how to deal with that to instead discuss how to deal with a fork and updated the main thread of the docs to talk about working with the main repo. I think that distinction was the main source of issues Rob ran into.
I also added some docs for conda-forge. Thankfully conda-forge is mostly automated so there's not much manual interaction besides merging bot-generated PRs, unless something breaks.

Update release instructions

---

docs/wiki/dev-guides/Release-Process.md

slight tweak on https://github.com/Point72/csp/pull/249 which I didn't notice, this makes it a more prominent note:
vs

Make tag info a more prominent note

---

cpp/csp/python/CMakeLists.txt
cpp/csp/python/PyStruct.cpp
cpp/csp/python/PyStructToDict.cpp
cpp/csp/python/PyStructToDict.h
csp/impl/struct.py

This PR adds a new `to_dict` method for structs which is written fully in C++.
The older python based `to_dict` method has been renamed to `to_dict_depr`.
Motivation:
The newer C++ based `to_dict` method is faster than the original python based `to_dict` method.
Some timing examples are shown below:
```
class A(csp.Struct):
a: int
b: str
c: bool
d: float
a = A(a=1, b="1", c=True, d=1.0)
%timeit a.to_dict()         # 0.888 microseconds
%timeit a.to_dict_depr()    # 4.98 microseconds
class E(csp.Struct):
a: list
b: dict
c: tuple
d: set
e = E(a=[1,2,3], b={1:1, 2:2, 3:3}, c=(1,2,3), d={1,2,3})
%timeit e.to_dict()        # 2.65 microseconds
%timeit e.to_dict_depr()   # 15.4 microseconds
```

Add native to_dict method for structs

---

cpp/csp/cppnodes/statsimpl.h

the decay multiplier can be pre-computed saving a call to log() [note that log( 2.0 ) is currently resulting in a call to log as it is not constexpr until C++26] and division per update
also prefer x*x vs pow( x, 2 ) to avoid relying on compiler to optimize this

Optimize halflife-based EMA's in csp.stats

---

cpp/csp/python/PyStructToDict.cpp
csp/impl/struct.py
csp/tests/impl/test_struct.py

This PR adds `postprocess_to_dict` hook to the `structs`.
This hook is invoked by the `to_dict` method on the `dict` obtained from parsing a `struct`. It will allows users to customize the final `dict` generated by the `to_dict` method for each struct.
```
class A(Struct):
replace_me: str
data: int = 0
def postprocess_to_dict(self, obj_dict):
obj_dict['replace_me'] = 'replace_me'
obj_dict['postprocess_invoked'] = True
return obj_dict
a = A(replace_me='Dummy', data=1)
a.to_dict() == {'replace_me': 'replace_me', 'data': 1, 'postprocess_invoked': True}
```

Add postprocess_to_dict hook for to_dict method in structs

---

csp/impl/types/instantiation_type_resolver.py
csp/tests/test_type_checking.py

Resolve empty container types as the generic form of the container

---

conda/dev-environment-unix.yml
conda/dev-environment-win.yml
csp/adapters/db.py
csp/build/csp_autogen.py
csp/impl/pandas_accessor.py
csp/impl/struct.py
csp/tests/impl/test_struct.py
csp/tests/test_baselib.py
pyproject.toml

For PEP8 compliance. The old functions still exist (added a new unit test), but are tagged as deprecated using the `deprecated` module.

Deprecate defineStruct and defineNestedStruct in favor of define_struct and define_nested_struct

---

cpp/csp/cppnodes/statsimpl.h
vcpkg.json

Improve implementation of statistics functions Quantile/Rank using `boost::multi_index`

---

docs/wiki/concepts/Common-Mistakes.md

Add "Common Mistakes" page for new users

---

docs/wiki/_Sidebar.md

Add "Common Mistakes" page to wiki Sidebar

---

cpp/csp/python/PyStructToJson.cpp
csp/tests/impl/test_struct.py
docs/wiki/api-references/csp.Struct-API.md

This PR adds support for more python types to be keys of a dictionary in the csp.Struct's to_json method.
Previously there was support for:
- strings
- integers
- floats
With this PR, the following additional types will be handled:
- None literal
- bools
- datetime, date, time (convert to ISO 8601 format)
- csp.Enums (use the name attribute to convert to string)
- Python enums (use the name attribute to convert to string)

Add support for additional python types as dict keys in Struct.to_json

---

csp/impl/wiring/adapters.py
csp/impl/wiring/signature.py
csp/tests/impl/test_outputadapter.py
csp/tests/impl/test_pushadapter.py

Add signature to adapters so that help works as expected

---

docs/wiki/api-references/Base-Nodes-API.md
docs/wiki/concepts/Common-Mistakes.md
docs/wiki/concepts/Execution-Modes.md

Closes #291 
Fixes mistake from #339

Document in detail how duplicate timestamps are handled

---

.github/workflows/build.yml
.github/workflows/conda.yml
.github/workflows/wiki-lint.yml
conda/dev-environment-unix.yml
conda/dev-environment-win.yml
cpp/csp/core/Enum.h
cpp/csp/cppnodes/statsimpl.h
pyproject.toml

https://github.com/pypa/setuptools/issues/4612
Full build: https://github.com/Point72/csp/actions/runs/10686944968

Pin back setuptools until we can remove distutils

---

cpp/csp/core/Time.h

Semantically align the "minimum" value for `Time` with `DateTime` & `TimeDelta` (e.g. `::MIN_VALUE`). Also, this avoids conflicts with other headers that rely on a `MIN` macro.

Change Time::MIN to Time::MIN_VALUE to match DateTime

---

conda/dev-environment-unix.yml
conda/dev-environment-win.yml
csp/impl/types/container_type_normalizer.py
csp/tests/impl/test_struct.py
pyproject.toml

Resolves https://github.com/Point72/csp/issues/373
See test case for usage/impact.
Annotations are particularly useful for adding information about validation and serialization at a field level (or any other field level metadata). Their use is completely optional and they are ignored pretty much everywhere unless you call Struct.metadata(typed=True).

Add support for Annotated to struct type.

---

conda/dev-environment-unix.yml
conda/dev-environment-win.yml
csp/impl/types/common_definitions.py
csp/impl/types/instantiation_type_resolver.py
csp/impl/types/pydantic_type_resolver.py
csp/impl/types/pydantic_types.py
csp/impl/types/tstype.py
csp/impl/types/typing_utils.py
csp/impl/wiring/edge.py
csp/impl/wiring/graph.py
csp/impl/wiring/signature.py
csp/tests/impl/types/test_pydantic_type_resolver.py
csp/tests/impl/types/test_pydantic_types.py
csp/tests/impl/types/test_tstype.py
csp/tests/impl/wiring/test_edge.py
csp/tests/test_baselib.py
csp/tests/test_engine.py
csp/tests/test_parsing.py
csp/tests/test_type_checking.py
csp/tests/test_typing.py
csp/typing.py
pyproject.toml

Please read the below. 
I have run all unit tests locally with and without pydantic type checking enabled, so the changes are fully compatible (though exception messages have changed).
**Open Issues**
The main open issues are
1. Need to agree on how to enable it and roll it out. It's currently done through an env variable, so that that the existing behavior is the default, and pydantic type checking (and import-dependency) is opt-in. Here's what I suggest
- Merge these changes (with no pydantic runtime dependency)
- Bump version to 0.8 (higher than internal version)
- Warn users that we will soon have a pydantic 2 dependency (in case they are still on pydantic v1)
- After some time (TBD), enable pydantic type checking by default if pydantic is importable. 
- After some time (TBD), add the …

Pydantic-based type checking

---

conda/dev-environment-unix.yml
conda/dev-environment-win.yml
cpp/csp/adapters/utils/ProtobufHelper.cpp

Change should be backward compatible with protobuf 4 (`AddError` was present but deprecated, `RecordError` present)
This is enforced (for now) via CI as conda has 5 but vcpkg has 4 (xref https://github.com/microsoft/vcpkg/pull/39800)

Support protobuf 5

---

CMakeLists.txt
Makefile
cpp/csp/adapters/kafka/KafkaAdapterManager.h
cpp/csp/adapters/parquet/DialectGenericListReaderInterface.h
cpp/csp/adapters/parquet/ParquetInputAdapterManager.h
cpp/csp/adapters/parquet/ParquetOutputAdapterManager.h
cpp/csp/adapters/parquet/ParquetReaderColumnAdapter.cpp
cpp/csp/adapters/websocket/ClientAdapterManager.h
cpp/csp/core/Exception.h
cpp/csp/core/Platform.h
cpp/csp/engine/AdapterManager.h
cpp/csp/engine/Feedback.h
cpp/csp/engine/Struct.h
cpp/csp/python/Exception.h
cpp/csp/python/InitHelper.h
cpp/csp/python/PyCspEnum.h
cpp/csp/python/adapters/CMakeLists.txt
csp/build/csp_autogen.py

@svatasoiu and I have been trying for a while to get symbol visibility correct for users wanting to build extension modules. Unfortunately there have been some complications with Windows support so in the meantime, we will revert the hidden visibility change we made earlier.
Confirmed that the example extension modules work again after this reversion.

Revert symbol visibility changes

---

.github/workflows/build.yml
conda/dev-environment-unix.yml
conda/dev-environment-win.yml
csp/adapters/perspective.py
csp/dataframe.py
csp/impl/pandas_perspective.py
csp/impl/perspective_common.py
csp/tests/adapters/test_perspective.py
csp/tests/impl/test_pandas_perspective.py
pyproject.toml

Many thanks to @sinistersnare for #370 which I relied on heavily for this PR. 
Some key differences from that PR are:
- Backwards compatibility for previous versions
- Take advantage of new `to_dataframe` function on the view
- Added perspective to automated testing by including it as a test dependency
- Disable `localize` option that allows for local timestamps in perspective, as it doesn't make sense on perspective 3.
I have explicitly checked that the tests pass under versions 2.10.1 and 3.1.4

Upgrade csp to perspective 3.x

---

examples/README.md

Fixes the formatting issue for "Complete Example (Retail)"

Fix table formatting in the examples README

---

.github/workflows/build.yml
.github/workflows/conda.yml

as per actions/runner-images#10721
Fixes #406

Remove macos-12 runner as it is fully unsupported as of 2024-12-03 

---

csp/impl/struct.py
csp/impl/types/container_type_normalizer.py
csp/tests/impl/test_struct.py

Fixes #405. 
In particular, since the type annotations are preserved when calling `.metadata(typed=True)`, they can then be used for runtime validation, which would not be the case if "str" (in the case of Literal) or object (in the case of Union) was used directly, Of course, by using Union one loses the benefits of being able to operate on the data in C++, but this is already true of "object", so the validation capabilities are a strict improvement.

Support Literal and Union/Optional types on structs. Fixes #405

---

.github/workflows/build.yml

These workflows will run on Mondays and Thursdays at 08:25 UTC (3:25 am EST). @timkpaine mentioned that daily builds will fill up our build cache and as a result slow down main/PR builds, so I think biweekly is enough to catch issues as they arise (considering we do not have super frequent commits). However, the frequency we run these full builds can be discussed more.

Add automatic full CI builds that run twice a week

---

Makefile

Fixes the current build failures on main
Test branch running in CI here: https://github.com/Point72/csp/actions/runs/12262509483/job/34211976946

Pin cmake on Windows builds to 3.31.1 as the new patch release is failing to install on GitHub Actions

---

Makefile

This reverts commit 1054f5caaa7c2d041f91a458789a8fdae2a84305.
I noticed `main` builds like [this one](https://github.com/Point72/csp/actions/runs/12302042801/job/34437998343 ) were failing as of Friday with the following error message:
```
Failures
- cmake - Failed to install cmake because a previous dependency failed.
- cmake.install - A newer version of cmake.install (v3.31.2) is already installed.
Use --allow-downgrade or --force to attempt to install older versions.
make: *** [Makefile:208: dependencies-win] Error 1
Error: Process completed with exit code 2.
```
I was going to add that flag but I first tried reverting the commit that pinned the cmake version, since we never knew why it was failing to install on GH Actions in the first place. Lo and behold the new cmake version …

Revert pinned cmake version on Windows builds

---

conda/dev-environment-unix.yml
conda/dev-environment-win.yml
cpp/csp/adapters/websocket/WebsocketEndpoint.cpp

This adds `zlib` as a direct dependency of the conda environment file rather than having it pulled in transitively from `thrift`, which is itself pulled in transitively from `arrow`. GH Actions was finding a outdated `zlib` version (1.3) in the conda end-to-end test without having it directly listed in the environment, although I'm not sure why 🤷. 
Also, as we haven't run a conda build for about 3 weeks, boost upgraded from 1.86.0 to 1.87.0 in December which is causing a build failure in the websocket code. This is a one-line fix.

Add zlib dependency to conda dev environment and update websocket code for boost 1.87

---

.github/workflows/conda.yml

This PR schedules automatic builds/tests for conda end-to-end tests every Mon/Thurs at 1:25 am EST. The goal is to catch issues causing build failures quickly so that PRs don't get stuck on unrelated dependency/build issues.

Scheduled CI builds for CSP conda end-to-end tests

---

conda/dev-environment-unix.yml
conda/dev-environment-win.yml
pyproject.toml

It seems there is some ABI incompatibility on x86 Mac between our vendored C++ Pyarrow code (version 16.0) and the recently-released Pyarrow 19.0 Python code, which is resulting in files being produced from the ParquetWriter that are unreadable in Python. See: https://github.com/Point72/csp/actions/runs/12863970430/job/35865078010
Discussed with @timkpaine and there are two options: 1) pin back pyarrow to <19 to avoid the Python side upgrade and 2) upgrade our vendored C++ code to a higher version which is compatible. Due to other bugs in pyarrow 19 (see https://github.com/apache/arrow/issues/45283) we decided to hold back on the upgrade until pyarrow 20.0, which (based on previous schedules) should come out in 2-3 months.

Pin pyarrow to <19 due to apparent incompatibility with vendored 16.0 Arrow C++ code on x86 macos

---

Makefile
cpp/cmake/modules/FindDepsKafkaAdapter.cmake
cpp/csp/adapters/kafka/CMakeLists.txt
pyproject.toml
vcpkg.json

As title, builds `librdkafka` with GSSAPI support via `cyrus-sasl`, enabling this feature for our pip packages (currently this only works on our conda packages). 
No windows support for now as vcpkg krb5 does not support our static build, will make a separate ticket to track
xref: https://github.com/microsoft/vcpkg/issues/40320

Build librdkafka with gssapi support for pip package, fixes #325

---

csp/tests/test_engine.py

I've noticed this test failing sporadically on our scheduled builds, like: https://github.com/Point72/csp/actions/runs/13366028175/job/37327469976. Since the comment states the leak would increase RSS memory by at least 50 MB, we can increase leeway from 5 MB to 10 MB to reduce noise from this test (for example, it used 7.3 MB in the failed run above).

Increase leeway for test_alarm_leak, which uses more memory on GH Actions runs

---

CMakeLists.txt
csp/__init__.py
pyproject.toml
setup.py

Full build: https://github.com/Point72/csp/actions/runs/13599251469
Adds in the patch for a missing pydantic dep in https://github.com/Point72/csp/pull/461

Release v0.0.11

---

csp/impl/types/pydantic_types.py
csp/impl/types/typing_utils.py
csp/tests/impl/types/test_pydantic_type_resolver.py
csp/tests/impl/types/test_tstype.py

Also improve error messages when incorrectly using  generic type (improves error messages for #469).

Handle `Any` type properly in pydantic type checking. Fixes #468

---

csp/impl/struct.py
csp/impl/types/container_type_normalizer.py
csp/impl/types/pydantic_types.py
csp/impl/types/type_annotation_normalizer_transformer.py
csp/impl/types/typing_utils.py
csp/tests/impl/test_struct.py
csp/tests/impl/types/test_pydantic_types.py
csp/tests/test_type_checking.py

This fixes a few issues all related to handling Union and Literals in type annotations. Namely:
1.
fixes https://github.com/Point72/csp/issues/475
Previously, the AST parsing for type annotations was incorrectly converting "None" in the example above to be a TypeVar, and then when we called `exec` on the new transformed AST, an error was being thrown. We make sure that in the AST parsing, we only convert a string to a TypeVar. 
2. 
fixes #481
We also handle the case with Literal, where before if you had `Literal["a", "b"]`, "a" and "b" were incorrectly assumed to be CspTypeVar, when they should be the actual literal value. For adjusting the annotations, we stop now if we encounter a `Literal` annotation.
3.
fixes #482
Related to the `Literal` and `Union` typing, when `from_dict` on …

Handle union and literal typing correctly in annotations

---

csp/impl/struct.py
csp/impl/types/typing_utils.py
csp/tests/impl/test_struct.py

Allow utilizing pydantic validaiton in `from_dict` via a new boolean flag. Add a core schema for the FastList to work with pydantic.
Running some simple benchmarks, it seems that the default `to_dict` and `to_json` for csp Structs are significantly faster than going the pydantic route. While pydantic does allow for custom serialization and deserialization, the callbacks in `to_dict` and `to_json` allow that flexibility as well. Thus, for most use-cases, I believe those are probably preferred.
However, going through pydantic for `from_dict` is faster and more correct than the current csp implementation (more correct as in respects the type annotations more strictly). Thus, it should be preferred. However, this might cause breaking changes for users, so I propose we introduce it as an …

Allow using pydantic for from_dict, schema for FastList

---

csp/impl/types/pydantic_types.py
csp/tests/impl/types/test_pydantic_types.py
csp/tests/test_basketlib.py

Fixes #483. Required for revalidation of output basket types when an int type is present.
The original adjustment of annotations converts `OutputBasketContainer` to `OutputBasket`. So when re-validating the `int`-based outputs after type var resolution, it needs to be able to handle the `OutputBasket` type, which it wasn't doing before. This PR fixes that issue, and also adds an explicit test for `csp.basketlib.sync` for a dict basket with int types, in addition to unit tests on the annotation adjustment.

Correct adjustment of annotations on OutputBasket type. Fixes #483.

---

csp/impl/struct.py
docs/wiki/api-references/csp.Struct-API.md

This PR fixes #498 
- Remove unnecessary python round trip in to_dict
- Add documentation for to_dict, to_dict_depr, postprocess_to_dict methods
Some timing examples are shown below:
```
class A(csp.Struct):
a: int
b: str
c: bool
d: float
a = A(a=1, b="1", c=True, d=1.0)
%timeit a.to_dict()         # 1.25 microseconds
%timeit a.to_dict()         # 0.99 microseconds
class E(csp.Struct):
a: list
b: dict
c: tuple
d: set
e = E(a=[1,2,3], b={1:1, 2:2, 3:3}, c=(1,2,3), d={1,2,3})
%timeit a.to_dict()         # 3.01 microseconds
%timeit a.to_dict()         # 2.56 microseconds
```

Improve performance of to_dict, and update docs

---

csp/impl/wiring/base_parser.py
csp/tests/test_type_checking.py

Special case None, so `Optional[ts...` is allowed
This applies to both csp.graphs and csp.nodes
Addresses https://github.com/Point72/csp/issues/495

Throw on parse if an input is a Union of ts and scalars.

---

Makefile

Test run: https://github.com/Point72/csp/actions/runs/14174868460/job/39707225211
Fixes #508 temporarily until vcpkg ports are updated to be cmake 4.0 compatible

Pin cmake to <4 as 4 is not compatible with external deps which allow <3.5

---

.github/workflows/build.yml

GH Actions removed the ubuntu 20.04 runner on 2025-04-15, this is causing "test_dependencies" to fail https://github.com/actions/runner-images/issues/11101
Kicked off full run here: https://github.com/Point72/csp/actions/runs/14598551138

Upgrade ubuntu runner version for test_dependencies, builds are failing as its retired

---

conda/dev-environment-unix.yml
conda/dev-environment-win.yml

Used in our code for debugging ast modifications (debug_print=True requires this package)

Add missing astor package to development environment

---

cpp/csp/python/PyStructToDict.cpp
csp/impl/struct.py
csp/tests/impl/test_struct.py

This is a breaking change as it involves changing the API interface for `postprocess_to_dict`.
The current definition for `postprocess_to_dict` just takes the dictionary as argument.
With this PR, `postprocess_to_dict` will take struct instance (`self`) and the dictionary for that `struct` as arguments.
The previous API did not allow modifying the dictionary based on the state of the `struct` instance.

Take self as argument in postprocess_to_dict

---

cpp/csp/python/adapters/parquetadapterimpl.cpp
csp/adapters/parquet.py

We previously used the `Arrow IPC` interface in the `ParquetAdapter` to pass data from `Python` to `C++`. This would result in the data getting serialized involving additional compute and data copy. We were not able to use the zero-copy interface before due to lack of a portable zero-copy method for arrow data.
The [`PyCapsule` interface](https://arrow.apache.org/docs/format/CDataInterface/PyCapsuleInterface.html), enables easy zero-copy movement of data through the stable C data interface. This PR resolves #212.
This PR replaces the `IPC` transfer logic with the `PyCapsule` interface to pass data from `Python` to `C++` zero-copy.
This also results in some performance improvements:
```
import csp
from csp.adapters.parquet import ParquetReader
import pyarrow as pa
class …
```

Use zero-copy C data interface in Parquet adapter

---

Makefile
cpp/csp/cppnodes/statsimpl.cpp
cpp/csp/python/cspstatsimpl.cpp
csp/stats.py
csp/tests/test_stats.py
docs/wiki/api-references/Statistical-Nodes-API.md

Additional API option that does not throw on out-of-sync ticks in a bivariate stats calc (addresses https://github.com/Point72/csp/issues/546). Non-breaking change to the APIs of `cov`, `corr` and `ema_cov`.

Add allow_non_overlapping parameter for bivariate statistics

---

cpp/csp/cppnodes/statsimpl.h
csp/tests/test_stats.py

Fix NaN handling bug in adjusted, unbiased ema_cov with a finite horizon and ignore_na=True

---

cpp/csp/cppnodes/statsimpl.h
csp/tests/test_stats.py

Avoid numerical imprecision for rolling variance in the case all values are identical

---

csp/adapters/arrow.py
csp/tests/adapters/test_arrow.py

#519 uses some APIs in `pyarrow` which are only available in version 19 and above (like `concat_batches` and `RecordBatch.cast`)
This PR adds support for running with older versions of `pyarrow`

Bugfix: Support arrow adapter for arrow versions <19

---

cpp/csp/python/PyBasketInputProxy.cpp
cpp/csp/python/PyBasketOutputProxy.cpp
cpp/csp/python/PyCspEnum.cpp
cpp/csp/python/PyOutputProxy.cpp
cpp/csp/python/PyStruct.cpp
cpp/tests/core/test_dynamicbitset.cpp

GH Actions runners updated gcc from 13.3 to 14.3 which caused the scheduled build to failure. Two changes:
1. It looks like gcc 14.3 has an errant warning on CSP objects when calling `Py_TYPE( self )` in destructor/free functions. The function is inlined and accesses the `ob_type` member of the object, but the compiler thinks the object has been destroyed since we called its destructor on the line above. Example:
```raw
In function 'PyTypeObject* Py_TYPE(PyObject*)',
inlined from 'void csp::python::PyStruct_dealloc(PyStruct*)' at /data01/home/ag11460/user/github/csp/cpp/csp/python/PyStruct.cpp:771:5:
/data01/home/ag11460/y/envs/csp/include/python3.12/object.h:220:16: error: '*(PyObject*)self._object::ob_type' is used uninitialized [-Werror=uninitialized]
220 |     return ob->ob_type;
| …
```

Fix conda build for gcc 14.3

---

cpp/csp/cppnodes/statsimpl.cpp
cpp/csp/cppnodes/statsimpl.h
cpp/csp/python/cspnpstatsimpl.cpp
cpp/csp/python/cspstatsimpl.cpp
cpp/csp/python/npstatsimpl.cpp
csp/stats.py
csp/tests/test_stats.py
docs/wiki/api-references/Statistical-Nodes-API.md

Closes #564. Also adds support for unbiased, unadjusted halflife (co)variance and cleans up some other things in the stats code.

Add support for unadjusted halflife-based EMA calculations

---

cpp/csp/python/PyStruct.cpp
cpp/csp/python/PyStruct.h
csp/tests/impl/test_struct.py

Note that there is no good way to avoid just keeping strong circular references here, effectively "leaking" dynamic struct types.

fixes #579 - PyStruct type refcount bug

---

Makefile
vcpkg.json

Pulls in patch for cyrus-sasl to include missing headers. At new baseline, we'd pull in arrow 21, so need to add an override for that as well.

Update vcpkg baseline to fix build for gcc 14

---

conda/dev-environment-unix.yml
conda/dev-environment-win.yml
cpp/csp/adapters/parquet/ParquetFileReaderWrapper.cpp
cpp/csp/adapters/parquet/ParquetFileWriterWrapper.cpp
pyproject.toml
vcpkg.json

tested against 20 locally, moving vcpkg and conda to 21 (for https://github.com/conda-forge/csp-feedstock/pull/79)

Add build support for arrow/parquet 20 and 21
