Point72/csp

- examples/3_using_adapters/e_11_websocket_output.py
> Fix failing websocket adapter example

- csp/baselib.py
- Fix type annotation for `csp.apply`
> Fix type annotation for `csp.apply`

- csp/impl/wiring/edge.py
- examples/2_intermediate/e_18_pandas_extension_example.py
Ported the pandas extension type example to remove internal dependencies.
> Add example for the pandas extension types

- csp/adapters/symphony.py
- csp/tests/adapters/test_symphony.py
- pyproject.toml
Fixes https://github.com/Point72/csp/issues/86
Needs:
> Symphony adapter

- Makefile
- README.md
- dev-environment.yml
- docs/wiki/0.-Introduction.md
- docs/wiki/1.-Generic-Nodes-(csp.baselib).md
- docs/wiki/2.-Math-Nodes-(csp.math).md
- docs/wiki/3.-Statistics-Nodes-(csp.stats).md
- docs/wiki/4.-Random-Time-Series-Generation-(csp.random).md
- docs/wiki/5.-Adapters.md
- docs/wiki/6.-Dynamic-Graphs.md
- docs/wiki/7.-csp.Struct.md
- docs/wiki/8.-Profiler.md
- docs/wiki/9.-Caching.md
- docs/wiki/98.-Building-From-Source.md
- docs/wiki/99.-Developer.md
- docs/wiki/Home.md
- examples/README.md
- pyproject.toml
> Lint and format docs

- cpp/csp/engine/CspType.h
- cpp/csp/engine/DialectGenericType.h
- cpp/csp/engine/Struct.cpp
- cpp/csp/engine/Struct.h
- cpp/csp/python/PyCspType.cpp
- cpp/csp/python/PyStruct.cpp
- csp/tests/impl/test_struct.py
Implementation of struct deepcopy.
Will allow to fix #69.
> Struct deepcopy implementation

- csp/math.py
[Rob commented](https://github.com/Point72/csp/pull/145/files#r1523870463) after I merged #145
> drop python version check in csp/math.py

- .github/workflows/build.yml
- Makefile
- pyproject.toml
moved from https://github.com/Point72/csp/pull/115
> Use manylinux-2-28 image for wheel builds

- vcpkg.json
Upgrade vcpkg to `43d81795a513e2ca6648354786178714f33c8b6f`
Update baseline to `8a12a368c8af1e39fa597793fb58555f54414d0b` (latest version is not stable)
> Upgrade baseline in vcpkg.json

- vcpkg.json
> Revert "Upgrade baseline in vcpkg.json"

- cpp/csp/adapters/websocket/ClientInputAdapter.cpp
- cpp/csp/adapters/websocket/ClientInputAdapter.h
- cpp/csp/adapters/websocket/ClientOutputAdapter.h
- csp/tests/adapters/test_websocket.py
Fix for https://github.com/Point72/csp/issues/217 
Added in tests for websocket client adapter.
> Fix JSONTextMessageMapper Bug in WebsocketAdapterManager

- .bumpversion.cfg
- Makefile
Let me know if we still don't want to commit, in which case we can do it via config which is better than the makefile commands.
> Sign commit when using bump version

- cpp/csp/python/PyStructToJson.cpp
This PR fixes a memory leak in the `to_json` method for structs.
> Fix memory leak in `DialectGenericType` in to_json

- examples/07_end_to_end/README.md
- examples/07_end_to_end/seismic_waveform.ipynb
It's in a reasonably presentable state, but could always use further improvements.
> First cut of seismic waveform example

- conda/dev-environment-unix.yml
- conda/dev-environment-win.yml
- pyproject.toml
xref https://github.com/Point72/csp/issues/58
> Force numpy<2 for now

- .bumpversion.cfg
- CMakeLists.txt
- csp/__init__.py
- pyproject.toml
- setup.py
release v0.0.5
Test results: https://github.com/Point72/csp/actions/runs/9681747126/job/26716266449
> release v0.0.5

- NOTICE
- vcpkg.json
> Update vcpkg baseline for bugfixes

- docs/wiki/_Sidebar.md
- docs/wiki/api-references/Graph-Utilities-API.md
> Document `csp.run`, `csp.run_on_thread` and `csp.show_graph`

- csp/impl/struct.py
- csp/tests/impl/test_struct.py
> Fix struct __dir__ implementation

- CMakeLists.txt
- conda/dev-environment-unix.yml
- conda/dev-environment-win.yml
- cpp/cmake/modules/FindCSP.cmake
- cpp/cmake/modules/Findcsp_autogen.cmake
- cpp/csp/core/Platform.h
- examples/05_cpp/2_cpp_node_with_struct/CMakeLists.txt
- examples/05_cpp/2_cpp_node_with_struct/README.md
- examples/05_cpp/2_cpp_node_with_struct/struct.cpp
xref: https://github.com/Point72/csp/issues/363
> Consolidate csp-autogen impls, fix struct cpp example

- cpp/csp/adapters/kafka/KafkaAdapterManager.cpp
- csp/adapters/kafka.py
- csp/adapters/utils.py
- Add proper memoization to adapter manager python object
- Tick all warning+ events from kafka to status
- Treat all brokers down as a fatal shutdown event
- Improve docstring on publish
> Kafka improvements

- csp/tests/impl/test_pandas_perspective.py
Running full CI/CD build here: https://github.com/Point72/csp/actions/runs/12161098426
> Fix perspective test for win32 build

- CMakeLists.txt
- csp/tests/adapters/test_websocket.py
- pyproject.toml
Run websocket tests, resolves #400
> Run websocket tests

- CMakeLists.txt
- csp/__init__.py
- pyproject.toml
- setup.py
Successful full build here: https://github.com/Point72/csp/actions/runs/12168252067
> Release v0.0.6

- CMakeLists.txt
- csp/__init__.py
- pyproject.toml
- setup.py
Manual CI run: https://github.com/Point72/csp/actions/runs/13011568256
> Release v0.0.7

- csp/__init__.py
> Enable full stack trace if CSP_PRINT_EXCEPTION_FULL_STACK is set

- CMakeLists.txt
- csp/__init__.py
- pyproject.toml
- setup.py
fullbuild: https://github.com/Point72/csp/actions/runs/13463924225
> CSP v0.0.9

- CMakeLists.txt
- csp/__init__.py
- pyproject.toml
- setup.py
build results: https://github.com/Point72/csp/actions/runs/13566793198/job/37921614046
> CSP v0.0.10

- CMakeLists.txt
- csp/__init__.py
- pyproject.toml
- setup.py
Build results: https://github.com/Point72/csp/actions/runs/13768540583
> CSP v0.8.0

- csp/impl/wiring/edge.py
- csp/tests/test_type_checking.py
Fixes https://github.com/Point72/csp/issues/491
> Test for generic ts default

- csp/impl/struct.py
- csp/tests/impl/test_struct.py
> Manually mangle attribute for type adapter to avoid name conflicts

- CMakeLists.txt
- csp/__init__.py
- pyproject.toml
- setup.py
Full test run: https://github.com/Point72/csp/actions/runs/15198292037
> Release 0.10.0

- CMakeLists.txt
- csp/__init__.py
- pyproject.toml
- setup.py
Full test run: https://github.com/Point72/csp/actions/runs/15472996037
> Release v0.10.1

- docs/wiki/_Sidebar.md
- docs/wiki/api-references/Basket-Nodes-API.md
I noticed we are missing documentation for the utilities under `csp.basketlib`.
> Document the csp.basketlib library

- CMakeLists.txt
- csp/__init__.py
- pyproject.toml
- setup.py
Full CI run: https://github.com/Point72/csp/actions/runs/16806215541
> Release 0.11.2

- .github/workflows/conda.yml
skip on mac for now as it is a bit flakey due to mac nonsense
> Run sanitizer job once per week, skip on mac for now
